name: Build Project

on:
  workflow_run:
    workflows: ["Install Dependencies"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Dependencies
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Build Project
        run: npm run build

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
