name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  install:
    uses: ./.github/workflows/install.yml  # ✅ Теперь это работает!

  build:
    needs: install
    uses: ./.github/workflows/build.yml  # ✅ Ждёт установки зависимостей

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml  # ✅ Ждёт билда
